[[edge_functions]]
  path = "/api/latest-release"
  function = "getLatestRelease"

[functions]
  directory = "netlify/functions"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200